package ui;

import java.awt.Color;
import java.awt.Graphics;
import logic.GraphData;
import logic.Utilities;

public class GraphPanel extends javax.swing.JPanel {

    private GraphData data;
    
    public GraphPanel() {
        initComponents();
        this.data = new GraphData();
    }
    
    public GraphData getGraphData() {
        return this.data;
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int[] values = this.data.getValues();
        
        if (values.length > 0)
        {
            int width = this.getWidth();
            int rectWidth = width/values.length;
            double height = (double) this.getHeight();
            double rectHeight = height / Utilities.getMaxFromArray(values);
            
            for (int i = 0; i < values.length; i++)
            {
                g.setColor(Color.BLACK);
                g.fillRect(i*rectWidth, (int) (height - values[i]*rectHeight), rectWidth, (int) (values[i]*rectHeight) );
                g.setColor(Color.WHITE);
                g.drawRect(i*rectWidth, (int) (height - values[i]*rectHeight), rectWidth, (int) (values[i]*rectHeight) );
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
